package regenrolmentsys;


import java.awt.Color;
import java.awt.Dimension;



 
public class LogInUI extends javax.swing.JPanel {
    private MainFrame mf = null;
    /**
     * Creates new form LogInUI
     */
    public LogInUI(MainFrame mf) {
        initComponents();
        this.mf = mf;
        setSize(1280, 720);
        setMinimumSize(new Dimension(1280, 720));
        setMaximumSize(new Dimension(1280, 720));
        setVisible(true);
        setPreferredSize(new Dimension(1280, 720));
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogInBTN = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        MainLBL = new javax.swing.JLabel();
        PLMLogo = new javax.swing.JLabel();
        MinimizeBTN = new javax.swing.JButton();
        CloseBTN = new javax.swing.JButton();
        UserIcon = new javax.swing.JLabel();
        UsedIDField = new javax.swing.JTextField();
        EnrlmntLBL = new javax.swing.JLabel();
        LogInLBL = new javax.swing.JLabel();
        UserID = new javax.swing.JLabel();
        SupportBTN = new javax.swing.JButton();
        LogInPanel = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setBackground(new java.awt.Color(234, 230, 230));
        setLayout(null);

        LogInBTN.setBackground(new java.awt.Color(254, 86, 86));
        LogInBTN.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        LogInBTN.setForeground(new java.awt.Color(255, 255, 255));
        LogInBTN.setText("LOG IN");
        LogInBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 86, 86), 0));
        LogInBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogInBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogInBTNMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LogInBTNMousePressed(evt);
            }
        });
        LogInBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInBTNActionPerformed(evt);
            }
        });
        add(LogInBTN);
        LogInBTN.setBounds(840, 380, 240, 50);

        jPanel1.setBackground(new java.awt.Color(254, 86, 86));
        jPanel1.setLayout(null);

        MainLBL.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        MainLBL.setForeground(new java.awt.Color(255, 255, 255));
        MainLBL.setText("Enrollment System for Regular Students");
        jPanel1.add(MainLBL);
        MainLBL.setBounds(40, 0, 290, 30);

        PLMLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/PLM_Seal_2013.png"))); // NOI18N
        jPanel1.add(PLMLogo);
        PLMLogo.setBounds(10, 0, 30, 30);

        MinimizeBTN.setBackground(new java.awt.Color(254, 86, 86));
        MinimizeBTN.setFont(new java.awt.Font("Boldfinger", 0, 24)); // NOI18N
        MinimizeBTN.setForeground(new java.awt.Color(255, 255, 255));
        MinimizeBTN.setText("-");
        MinimizeBTN.setToolTipText("");
        MinimizeBTN.setBorder(null);
        MinimizeBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimizeBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizeBTNMouseExited(evt);
            }
        });
        MinimizeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizeBTNActionPerformed(evt);
            }
        });
        jPanel1.add(MinimizeBTN);
        MinimizeBTN.setBounds(1220, 0, 30, 30);

        CloseBTN.setBackground(new java.awt.Color(254, 86, 86));
        CloseBTN.setFont(new java.awt.Font("Boldfinger", 0, 18)); // NOI18N
        CloseBTN.setForeground(new java.awt.Color(255, 255, 255));
        CloseBTN.setText("X");
        CloseBTN.setBorder(null);
        CloseBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseBTNMouseExited(evt);
            }
        });
        CloseBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBTNActionPerformed(evt);
            }
        });
        jPanel1.add(CloseBTN);
        CloseBTN.setBounds(1250, 0, 30, 30);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 30);

        UserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/1077114.png"))); // NOI18N
        add(UserIcon);
        UserIcon.setBounds(1120, 210, 50, 70);

        UsedIDField.setBackground(new java.awt.Color(249, 248, 248));
        UsedIDField.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        UsedIDField.setToolTipText("");
        UsedIDField.setActionCommand("<Not Set>");
        UsedIDField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        UsedIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsedIDFieldActionPerformed(evt);
            }
        });
        add(UsedIDField);
        UsedIDField.setBounds(720, 210, 450, 70);

        EnrlmntLBL.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        EnrlmntLBL.setForeground(new java.awt.Color(255, 255, 255));
        EnrlmntLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EnrlmntLBL.setText("Enrollment System for Regular Students");
        EnrlmntLBL.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        EnrlmntLBL.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add(EnrlmntLBL);
        EnrlmntLBL.setBounds(70, 620, 520, 60);

        LogInLBL.setFont(new java.awt.Font("Poppins", 1, 48)); // NOI18N
        LogInLBL.setText("Log In");
        add(LogInLBL);
        LogInLBL.setBounds(690, 70, 190, 80);

        UserID.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        UserID.setText("User ID");
        add(UserID);
        UserID.setBounds(720, 180, 180, 30);

        SupportBTN.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        SupportBTN.setForeground(new java.awt.Color(254, 86, 86));
        SupportBTN.setText("Contact support");
        SupportBTN.setToolTipText("");
        SupportBTN.setBorder(null);
        SupportBTN.setContentAreaFilled(false);
        SupportBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupportBTNActionPerformed(evt);
            }
        });
        add(SupportBTN);
        SupportBTN.setBounds(890, 560, 140, 30);

        LogInPanel.setBackground(new java.awt.Color(255, 255, 255));
        LogInPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/white-color-solid-background-1920x1080.png"))); // NOI18N
        LogInPanel.setText("LOG IN");
        LogInPanel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        LogInPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        add(LogInPanel);
        LogInPanel.setBounds(660, 50, 600, 650);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/LogInShortFinal.gif"))); // NOI18N
        add(Background);
        Background.setBounds(0, 0, 1280, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void UsedIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsedIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsedIDFieldActionPerformed

    private void LogInBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogInBTNActionPerformed

    private void LogInBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInBTNMouseEntered
             LogInBTN.setBackground(new Color(203,68,68));     
            

             // TODO add your handling code here:
    }//GEN-LAST:event_LogInBTNMouseEntered

    private void LogInBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInBTNMouseExited
             LogInBTN.setBackground(new Color(254, 86, 86));
        // TODO add your handling code here:
    }//GEN-LAST:event_LogInBTNMouseExited

    private void SupportBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupportBTNActionPerformed
    //support
      
    }//GEN-LAST:event_SupportBTNActionPerformed

    private void LogInBTNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInBTNMousePressed
        //login
    }//GEN-LAST:event_LogInBTNMousePressed

    private void MinimizeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeBTNActionPerformed
//minimize
         
        // TODO add your handling code here:
    }//GEN-LAST:event_MinimizeBTNActionPerformed

    private void CloseBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBTNActionPerformed
         
         
         
        // TODO add your handling code here:
    }//GEN-LAST:event_CloseBTNActionPerformed

    private void MinimizeBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeBTNMouseEntered
        MinimizeBTN.setBackground(new Color(203,68,68));   
// TODO add your handling code here:
    }//GEN-LAST:event_MinimizeBTNMouseEntered

    private void CloseBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBTNMouseEntered
        CloseBTN.setBackground(new Color(203,68,68));   
        // TODO add your handling code here:
    }//GEN-LAST:event_CloseBTNMouseEntered

    private void MinimizeBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeBTNMouseExited
        MinimizeBTN.setBackground(new Color(254, 86, 86));
// TODO add your handling code here:
    }//GEN-LAST:event_MinimizeBTNMouseExited

    private void CloseBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBTNMouseExited
        CloseBTN.setBackground(new Color(254, 86, 86));
// TODO add your handling code here:
    }//GEN-LAST:event_CloseBTNMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton CloseBTN;
    private javax.swing.JLabel EnrlmntLBL;
    private javax.swing.JButton LogInBTN;
    private javax.swing.JLabel LogInLBL;
    private javax.swing.JLabel LogInPanel;
    private javax.swing.JLabel MainLBL;
    private javax.swing.JButton MinimizeBTN;
    private javax.swing.JLabel PLMLogo;
    private javax.swing.JButton SupportBTN;
    private javax.swing.JTextField UsedIDField;
    private javax.swing.JLabel UserID;
    private javax.swing.JLabel UserIcon;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
